version: '3.7'

services:
  backend:
    build: ./backend
    networks:
      - my-network
    depends_on:
      - database

  database:
    build: ./database
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - my-network

  httpd:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
