name: CI/CD with SonarCloud and Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-analyze-publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Install sonar-scanner
    - name: Install SonarScanner
      run: |
        curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
        unzip sonar-scanner.zip
        mv sonar-scanner-4.8.0.2856-linux sonar-scanner
        echo "PATH=$PATH:$PWD/sonar-scanner/bin" >> $GITHUB_ENV

    # Step 4: Run SonarCloud analysis
    - name: Analyze with SonarCloud
      run: |
        sonar-scanner \
          -Dsonar.projectKey=bigdatadevops \
          -Dsonar.organization=BigdataDevOps \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.sources=./backend

    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Step 6: Build and push Docker images
    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-network-backend ./backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-network-backend

    - name: Build and push database image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-network-database ./database
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-network-database

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-network-frontend ./frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-network-frontend
