name: CI/CD with SonarCloud and Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-analyze-publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build, test, and analyze with SonarCloud
    - name: Build, Test, and Analyze with SonarCloud
      run: |
        cd backend
        mvn -B verify sonar:sonar \
          -Dsonar.projectKey=bigdatadevops \
          -Dsonar.organization=BigdataDevOps \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Step 5: Build and push Docker images
    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-network-backend ./backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-network-backend

    - name: Build and push database image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-network-database ./database
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-network-database

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-network-frontend ./frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-network-frontend
