name: CI - Build and Test

# Trigger workflow on pushes to the repository
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build and test the backend
    - name: Build and test with Maven
      run: |
        cd backend
        mvn clean verify

    # Step 4: Build Docker images (optional for additional testing)
    - name: Build Docker images
      run: |
        docker build -t app-network-backend ./backend
        docker build -t app-network-database ./database
        docker build -t app-network-httpd ./frontend
